name: Execution of Unit Tests for the trail conditions ETL pipeline

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 1. Define the service directories
        service-dir:
          - categorize-trail-conditions
          - fetch-weather
          - schedule-jobs
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Sync Dependencies in ${{ matrix.service-dir }}
        working-directory: ${{ matrix.service-dir }}
        run: |
          # The service directory must contain a pyproject.toml for uv sync to work
          uv sync

      - name: Run Tests in ${{ matrix.service-dir }}
        working-directory: ${{ matrix.service-dir }}
        run: uv run pytest
